In [1]:
import numpy as np

# Construct Reward Matrix

In [2]:
R=np.matrix([
    
    [-1,-1,-1,-1,0,-1],
    [-1,-1,-1,0,-1,100],
    [-1,-1,-1,0,-1,-1],
    [-1,0,0,-1,0,-1],
    [-1,0,0,-1,-1,100],
    [-1,0,-1,-1,0,100]
])
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [ -1,   0,   0,  -1,  -1, 100],
        [ -1,   0,  -1,  -1,   0, 100]])

In [3]:
# Construct the Zero Matrix

In [4]:
Q=np.matrix(np.zeros([6,6]))
print(Q)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# Define Gama value- Learning Parameter

In [5]:
gamma=0.8

# Q- Learning:
    Q(state,action)=R(state,action)+gamma*Max(Q(next state,all actions))

# Initial state(usually to be choosen as random)

In [6]:
Initial_state=1

# Define the Available action function
This function returns all the available actions in the state given as an argumnet

In [7]:
def available_actions(state):
    current_state_row=R[state,]
    av_act=np.where(current_state_row>=0)[1]
    return av_act

In [8]:
available_act=available_actions(Initial_state)
print(available_act)

[3 5]


In [9]:
# Define the sample next action function

def sample_next_action(available_actions_range):
    next_action=int(np.random.choice(available_act,1))
    return next_action

In [10]:
action=sample_next_action(available_act)
print(action)


5


# Q Matrix - update function

In [11]:
def update(current_state,action,gamma):
 
    #Max(Q(next state,all actions))
    max_index=np.where(Q[action,]==np.max(Q[action,]))[1] 

    if max_index.shape[0]>1:
        max_index=int(np.random.choice(max_index,size=1))

    else:
        max_index=int(max_index)
    max_value=Q[action,max_index]

    Q[current_state,action]=R[current_state,action]+gamma*max_value

In [12]:
update(Initial_state,action,gamma)

# Train the agent with this environment information

In [18]:
for i in range(10000000):
    current_state=np.random.randint(0,int(Q.shape[0]))
    action=sample_next_action(available_act)
    update(current_state,action,gamma)

# Testing
goal_state=5

In [15]:
current_state=4
steps=[current_state]
while current_state!=5:
    next_step_index=np.where(Q[current_state,]==np.max(Q[current_state,]))[1]
    if next_step_index.shape[0]>1:
        next_step_index=int(np.random.choice(next_step_index,size=1))
    else:
        next_step_index=int(next_step_index)
    steps.append(next_step_index)
    current_state=next_step_index
 
print('Optimum path of initail state {} to the Goal State is {}'.format(Initial_state,steps))


Optimum path of initail state 1 to the Goal State is [4, 5]
